import Head from "next/head";
import { css } from "@emotion/react";
import { motion } from "framer-motion";

const color = "white";

export default function Home() {
  return (
    <>
      <Head>
        <title>Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        main
        <div
          css={css`
            padding: 32px;
            background-color: hotpink;
            font-size: 24px;
            border-radius: 4px;
            margin-bottom: 12px;
            &:hover {
              color: ${color};
            }
          `}
        >
          Hover to change color. (emotion test)
        </div>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 2 }}
        >
          opacity animation (framer motion test)
        </motion.div>
      </main>
    </>
  );
}
