# commit에 PR이라는 단어가 포함되어 있을 경우에만 PR을 생성하도록 설정
# 이미 PR을 생성한 경우에는 다시 PR을 생성하지 않도록 되어있음 

name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    if: ${{ (contains(github.event.head_commit.message, 'PR') || contains(github.event.head_commit.message, 'pr'))}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
        head: ${{ github.ref }}
        base: main
        title: ${{ github.event.head_commit.message }}


