
# 예시 코드는 아래와 같아. 
# name: "Create PR"
# on: push

# jobs:
#   create-pr-on-push:
#     if: ${{ (contains(github.event.head_commit.message, 'PR') || contains(github.event.head_commit.message, 'pr'))}}
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@1.0.0
#     - name: Create pull request
#       uses: thomaseizinger/create-pull-request@master
#       with:
#         GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
#         head: ${{ github.ref }}
#         base: main
#         title: ${{ github.event.head_commit.message }}


# commit에 PR이라는 단어가 포함되어 있을 경우에만 PR을 생성하도록 설정
# 이미 PR을 생성한 경우에는 다시 PR을 생성하지 않도록 되어있음 
# PR이 이미 생성되어있는 경우에, 새로운 commit을 push하면, 기존 PR의 내용애 commit 기록이 추가되도록 설정해야해. 

name: "Update PR"
on: push

jobs:
  update-pr-on-push:
    if: ${{ (contains(github.event.head_commit.message, 'PR') || contains(github.event.head_commit.message, 'pr'))}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Update pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
        commit-message: ${{ github.event.head_commit.message }}
        title: ${{ github.event.head_commit.message }}
        branch: ${{ github.ref }}
        base: main
        body: "This is an auto-generated PR. Please review."
        labels: "auto-generated, update"
        assignees: "sumi-0011"
        reviewers: "sumi-0011"